import { QueryResult } from '../types';

// This service simulates the Java Spring Boot 2.6.6 Backend
// In a real scenario, this would use fetch/axios to call your endpoints.

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const generateMockData = (sql: string): any[] => {
  const lowerSql = sql.toLowerCase();
  
  if (lowerSql.includes('users')) {
    return Array.from({ length: 15 }).map((_, i) => ({
      id: i + 1,
      username: `user_${i + 100}`,
      email: `user${i + 100}@example.com`,
      role: i % 3 === 0 ? 'ADMIN' : 'USER',
      created_at: new Date(Date.now() - Math.random() * 10000000000).toISOString(),
      status: Math.random() > 0.2 ? 'ACTIVE' : 'INACTIVE'
    }));
  }
  
  if (lowerSql.includes('orders')) {
    return Array.from({ length: 15 }).map((_, i) => ({
      order_id: `ORD-${2024000 + i}`,
      user_id: Math.floor(Math.random() * 100) + 1,
      amount: (Math.random() * 500).toFixed(2),
      currency: 'USD',
      status: ['PENDING', 'PAID', 'SHIPPED'][Math.floor(Math.random() * 3)],
      created_at: new Date().toISOString()
    }));
  }

  // Default generic data if table not recognized
  return Array.from({ length: 5 }).map((_, i) => ({
    col_1: `Value ${i}-A`,
    col_2: `Value ${i}-B`,
    col_3: Math.floor(Math.random() * 1000),
    notes: 'Mock data generated by frontend service'
  }));
};

export const executeQuery = async (sql: string): Promise<QueryResult> => {
  // Simulate network latency
  await delay(600 + Math.random() * 800);

  // Simulate Backend Validation (Spring Boot Layer)
  const forbidden = ['drop', 'delete', 'update', 'insert', 'truncate', 'alter'];
  if (forbidden.some(word => sql.toLowerCase().includes(word))) {
     throw new Error("SECURITY ALERT: Write operations are strictly forbidden. Read-only access.");
  }

  // Parse LIMIT for mock generation (heuristic)
  const limitMatch = sql.match(/limit\s+(\d+)/i);
  let limit = 100;
  if (limitMatch && limitMatch[1]) {
    limit = parseInt(limitMatch[1], 10);
  }

  const rawData = generateMockData(sql);
  const rows = rawData.slice(0, limit);
  const columns = rows.length > 0 ? Object.keys(rows[0]) : [];

  return {
    columns,
    rows,
    executionTimeMs: Math.floor(Math.random() * 200),
    totalRows: rows.length
  };
};
